command:
  - "bash"
  - "-c"
  - "export DATABASE_URL='postgresql://neondb_owner:npg_QsK4OwkaY3BE@ep-polished-mouse-a8jl2d6c-pooler.eastus2.azure.neon.tech/neondb?sslmode=require' && export SESSION_SECRET='my-secret-key-123' && export DATABRICKS_APP='true' && npm install && npm run build && npm run start"